# Generated by Django 3.2.7 on 2021-09-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='nullable',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
